2025-04-17 21:29:19,062 - iceberg-catalog - INFO - [database.py:11] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-17 21:29:19,069 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-17 21:29:19,069 - iceberg-catalog - INFO - [database.py:16] - Connecting to database...
2025-04-17 21:29:19,226 - iceberg-catalog - INFO - [database.py:20] - Successfully connected to database
2025-04-17 21:29:19,226 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-17 21:29:26,575 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: None
2025-04-17 21:29:26,576 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: default
2025-04-17 21:29:26,580 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:30:06,508 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-17 21:30:06,509 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-17 21:30:06,512 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/dev/
2025-04-17 21:30:06,513 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-17 21:30:06,514 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:35:25,466 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-17 21:35:25,467 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-17 21:35:25,512 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/dev/
2025-04-17 21:35:25,512 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-17 21:35:25,515 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:52:32,205 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: None
2025-04-17 21:52:32,207 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: default
2025-04-17 21:52:32,279 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:52:37,918 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-17 21:52:37,919 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-17 21:52:37,923 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:52:41,675 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/
2025-04-17 21:52:41,676 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/
2025-04-17 21:52:41,679 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-17 21:52:46,233 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: invalid-warehouse
2025-04-17 21:52:46,233 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: invalid-warehouse
2025-04-17 21:52:46,236 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: invalid-warehouse
2025-04-17 21:52:46,236 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-17 21:52:46,237 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 00:33:59,638 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 00:33:59,639 - iceberg-catalog - INFO - [database.py:29] - Disconnecting from database...
2025-04-18 00:33:59,640 - iceberg-catalog - INFO - [database.py:33] - Database connections closed
2025-04-18 00:33:59,641 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 00:50:11,718 - iceberg-catalog - INFO - [database.py:11] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 00:50:11,726 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 00:50:11,727 - iceberg-catalog - INFO - [database.py:16] - Connecting to database...
2025-04-18 00:50:11,727 - iceberg-catalog - ERROR - [database.py:24] - Failed to connect to database: invalid DSN: scheme is expected to be either "postgresql" or "postgres", got 'postgresql+asyncpg'
Traceback (most recent call last):
  File "/code/app/database.py", line 19, in connect
    self.pool = await asyncpg.create_pool(self.connection_string)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 1041, in _connect
    addrs, params, config = _parse_connect_arguments(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 749, in _parse_connect_arguments
    addrs, params = _parse_connect_dsn_and_args(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 283, in _parse_connect_dsn_and_args
    raise exceptions.ClientConfigurationError(
asyncpg.exceptions._base.ClientConfigurationError: invalid DSN: scheme is expected to be either "postgresql" or "postgres", got 'postgresql+asyncpg'
2025-04-18 00:54:13,224 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 00:54:13,231 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 00:54:13,231 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 00:54:13,393 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 00:54:13,393 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 00:54:19,441 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 00:54:19,443 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 00:54:19,453 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 00:54:19,453 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 00:55:53,189 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 00:55:53,196 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 00:55:53,196 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 00:55:53,358 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 00:55:53,359 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 00:55:59,310 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: None
2025-04-18 00:55:59,311 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: default
2025-04-18 00:55:59,322 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 00:56:07,565 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-18 00:56:07,566 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-18 00:56:07,568 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/dev/
2025-04-18 00:56:07,568 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-18 00:56:07,569 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:05:43,521 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-18 01:05:43,525 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-18 01:05:43,592 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:05:47,410 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/
2025-04-18 01:05:47,411 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/
2025-04-18 01:05:47,412 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:05:50,853 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/as
2025-04-18 01:05:50,855 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/as
2025-04-18 01:05:50,857 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/test/as
2025-04-18 01:05:50,858 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-18 01:05:50,859 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:06:28,746 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:06:28,748 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:06:28,751 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:06:28,752 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:16:59,398 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:16:59,406 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 01:16:59,406 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:16:59,559 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:16:59,560 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 01:17:08,037 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/as
2025-04-18 01:17:08,038 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/as
2025-04-18 01:17:08,055 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/test/as
2025-04-18 01:17:08,055 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-18 01:17:08,057 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:17:11,928 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/
2025-04-18 01:17:11,929 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/
2025-04-18 01:17:11,931 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:20:39,018 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:20:39,021 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:20:39,038 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:20:39,038 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:20:39,219 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:20:39,226 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 01:20:39,227 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:20:39,442 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:20:39,443 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 01:21:09,023 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:21:09,026 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:21:09,098 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:21:09,099 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:21:09,368 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:21:09,376 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 01:21:09,377 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:21:09,544 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:21:09,544 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 01:21:55,442 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:21:55,444 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:21:55,454 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:21:55,454 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:21:55,638 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:21:55,646 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 01:21:55,646 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:21:55,809 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:21:55,810 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 01:22:51,410 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:22:51,412 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:22:51,438 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:22:51,438 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:22:51,636 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:22:51,656 - iceberg-catalog - INFO - [main.py:39] - Starting up application
2025-04-18 01:22:51,656 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:22:51,814 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:22:51,814 - iceberg-catalog - INFO - [main.py:41] - Database connection established
2025-04-18 01:23:06,931 - iceberg-catalog - INFO - [main.py:45] - Shutting down application
2025-04-18 01:23:06,932 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:23:06,940 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:23:06,940 - iceberg-catalog - INFO - [main.py:47] - Database connection closed
2025-04-18 01:23:07,111 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:23:07,128 - iceberg-catalog - INFO - [main.py:40] - Starting up application
2025-04-18 01:23:07,129 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:23:07,281 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:23:07,281 - iceberg-catalog - INFO - [main.py:42] - Database connection established
2025-04-18 01:23:33,691 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: ss, parent: None, page_token: None, page_size: None
2025-04-18 01:23:33,692 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:23:33,697 - iceberg-catalog - ERROR - [database.py:74] - Database query error: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:23:33,699 - iceberg-catalog - ERROR - [namespace.py:118] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:23:33,699 - iceberg-catalog - ERROR - [namespaces.py:74] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/api/namespaces.py", line 44, in list_namespaces
    return await NamespaceService.list_namespaces(parent, page_token, page_size)
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:12,510 - iceberg-catalog - INFO - [namespaces.py:108] - Create namespace request. prefix: dev, namespace: ['namespace1']
2025-04-18 01:24:12,511 - iceberg-catalog - INFO - [namespace.py:126] - Creating namespace: ['namespace1']
2025-04-18 01:24:12,512 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 01:24:12,513 - iceberg-catalog - ERROR - [database.py:58] - Database query error: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:12,514 - iceberg-catalog - ERROR - [namespace.py:205] - Error checking namespace existence: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/services/namespace.py", line 202, in namespace_exists
    result = await db.fetch_one(query, namespace_levels)
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:12,514 - iceberg-catalog - ERROR - [namespaces.py:139] - Error creating namespace: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/api/namespaces.py", line 109, in create_namespace
    return await NamespaceService.create_namespace(request)
  File "/code/app/services/namespace.py", line 129, in create_namespace
    namespace_exists = await NamespaceService.namespace_exists(request.namespace.__root__)
  File "/code/app/services/namespace.py", line 202, in namespace_exists
    result = await db.fetch_one(query, namespace_levels)
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:27,170 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: ss, parent: None, page_token: None, page_size: None
2025-04-18 01:24:27,171 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:24:27,174 - iceberg-catalog - ERROR - [database.py:74] - Database query error: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:27,175 - iceberg-catalog - ERROR - [namespace.py:118] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:24:27,175 - iceberg-catalog - ERROR - [namespaces.py:74] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/api/namespaces.py", line 44, in list_namespaces
    return await NamespaceService.list_namespaces(parent, page_token, page_size)
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:25:13,450 - iceberg-catalog - INFO - [main.py:46] - Shutting down application
2025-04-18 01:25:13,453 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:25:13,460 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:25:13,461 - iceberg-catalog - INFO - [main.py:48] - Database connection closed
2025-04-18 01:25:27,548 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:25:27,577 - iceberg-catalog - INFO - [main.py:40] - Starting up application
2025-04-18 01:25:27,578 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:25:27,740 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:25:27,740 - iceberg-catalog - INFO - [main.py:42] - Database connection established
2025-04-18 01:25:34,380 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: ss, parent: None, page_token: None, page_size: None
2025-04-18 01:25:34,380 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:25:34,385 - iceberg-catalog - ERROR - [database.py:74] - Database query error: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:25:34,387 - iceberg-catalog - ERROR - [namespace.py:118] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:25:34,387 - iceberg-catalog - ERROR - [namespaces.py:74] - Error listing namespaces: relation "namespaces" does not exist
Traceback (most recent call last):
  File "/code/app/api/namespaces.py", line 44, in list_namespaces
    return await NamespaceService.list_namespaces(parent, page_token, page_size)
  File "/code/app/services/namespace.py", line 95, in list_namespaces
    namespace_records = await db.fetch_all(query, *params)
  File "/code/app/database.py", line 70, in fetch_all
    records = await conn.fetch(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 690, in fetch
    return await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "namespaces" does not exist
2025-04-18 01:26:31,597 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: ss, parent: None, page_token: None, page_size: None
2025-04-18 01:26:31,599 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:26:42,994 - iceberg-catalog - INFO - [namespaces.py:108] - Create namespace request. prefix: dev, namespace: ['namespace1']
2025-04-18 01:26:42,995 - iceberg-catalog - INFO - [namespace.py:126] - Creating namespace: ['namespace1']
2025-04-18 01:26:42,995 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 01:26:52,560 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: dev, parent: None, page_token: None, page_size: None
2025-04-18 01:26:52,561 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:27:06,909 - iceberg-catalog - INFO - [namespaces.py:171] - Load namespace metadata request. prefix: dev, namespace: namespace1
2025-04-18 01:27:06,911 - iceberg-catalog - INFO - [namespace.py:160] - Getting namespace metadata: ['namespace1']
2025-04-18 01:27:18,557 - iceberg-catalog - INFO - [namespaces.py:236] - Check namespace exists request. prefix: dev, namespace: namespace1
2025-04-18 01:27:18,558 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 01:27:21,779 - iceberg-catalog - INFO - [namespaces.py:236] - Check namespace exists request. prefix: dev, namespace: namespace11
2025-04-18 01:27:21,782 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace11']
2025-04-18 01:27:21,783 - iceberg-catalog - WARNING - [namespaces.py:241] - Namespace not found: namespace11
2025-04-18 01:27:56,890 - iceberg-catalog - INFO - [namespaces.py:365] - Update namespace properties request. prefix: dev, namespace: namespace1
2025-04-18 01:27:56,892 - iceberg-catalog - INFO - [namespace.py:259] - Updating namespace properties: ['namespace1']
2025-04-18 01:27:56,892 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 01:28:02,955 - iceberg-catalog - INFO - [namespaces.py:171] - Load namespace metadata request. prefix: dev, namespace: namespace1
2025-04-18 01:28:02,956 - iceberg-catalog - INFO - [namespace.py:160] - Getting namespace metadata: ['namespace1']
2025-04-18 01:28:43,868 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: devs, parent: None, page_token: None, page_size: None
2025-04-18 01:28:43,870 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:28:52,576 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix: ss, parent: None, page_token: None, page_size: None
2025-04-18 01:28:52,585 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:29:07,316 - iceberg-catalog - INFO - [namespaces.py:43] - List namespaces request. prefix:  , parent: None, page_token: None, page_size: None
2025-04-18 01:29:07,317 - iceberg-catalog - INFO - [namespace.py:51] - Listing namespaces. Parent: None, Page token: None, Page size: None
2025-04-18 01:44:23,170 - iceberg-catalog - INFO - [main.py:46] - Shutting down application
2025-04-18 01:44:23,172 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:44:23,173 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:44:23,173 - iceberg-catalog - INFO - [main.py:48] - Database connection closed
2025-04-18 01:44:23,398 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:44:23,415 - iceberg-catalog - INFO - [main.py:40] - Starting up application
2025-04-18 01:44:23,415 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:44:23,570 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:44:23,570 - iceberg-catalog - INFO - [main.py:42] - Database connection established
2025-04-18 01:44:52,911 - iceberg-catalog - INFO - [main.py:46] - Shutting down application
2025-04-18 01:44:52,915 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:44:52,932 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:44:52,933 - iceberg-catalog - INFO - [main.py:48] - Database connection closed
2025-04-18 01:44:53,133 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:45:19,966 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:45:19,985 - iceberg-catalog - INFO - [main.py:44] - Starting up application
2025-04-18 01:45:19,985 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:45:20,150 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:45:20,151 - iceberg-catalog - INFO - [main.py:46] - Database connection established
2025-04-18 01:45:49,765 - iceberg-catalog - INFO - [main.py:50] - Shutting down application
2025-04-18 01:45:49,767 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:45:49,783 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:45:49,784 - iceberg-catalog - INFO - [main.py:52] - Database connection closed
2025-04-18 01:45:50,017 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:45:50,035 - iceberg-catalog - INFO - [main.py:44] - Starting up application
2025-04-18 01:45:50,036 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:45:50,228 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:45:50,228 - iceberg-catalog - INFO - [main.py:46] - Database connection established
2025-04-18 01:51:09,779 - iceberg-catalog - INFO - [main.py:50] - Shutting down application
2025-04-18 01:51:09,783 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:51:09,785 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:51:09,785 - iceberg-catalog - INFO - [main.py:52] - Database connection closed
2025-04-18 01:51:09,975 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:51:09,993 - iceberg-catalog - INFO - [main.py:44] - Starting up application
2025-04-18 01:51:09,994 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:51:10,150 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:51:10,150 - iceberg-catalog - INFO - [main.py:46] - Database connection established
2025-04-18 01:51:39,311 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: None
2025-04-18 01:51:39,312 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: default
2025-04-18 01:51:39,319 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:51:44,913 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/dev/
2025-04-18 01:51:44,914 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/dev/
2025-04-18 01:51:44,915 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:51:47,975 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/ee/
2025-04-18 01:51:47,976 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/ee/
2025-04-18 01:51:47,977 - iceberg-catalog - INFO - [config.py:50] - No configuration found for catalog: s3://300289082521-my-warehouse/ee/
2025-04-18 01:51:47,977 - iceberg-catalog - INFO - [config.py:54] - Trying to fetch default configuration
2025-04-18 01:51:47,979 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:51:50,892 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: s3://300289082521-my-warehouse/test/
2025-04-18 01:51:50,893 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: s3://300289082521-my-warehouse/test/
2025-04-18 01:51:50,894 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 01:52:11,325 - iceberg-catalog - INFO - [main.py:50] - Shutting down application
2025-04-18 01:52:11,327 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:52:11,336 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:52:11,336 - iceberg-catalog - INFO - [main.py:52] - Database connection closed
2025-04-18 01:57:21,486 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 01:57:21,504 - iceberg-catalog - INFO - [main.py:44] - Starting up application
2025-04-18 01:57:21,504 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 01:57:21,672 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 01:57:21,673 - iceberg-catalog - INFO - [main.py:46] - Database connection established
2025-04-18 01:59:21,070 - iceberg-catalog - INFO - [main.py:50] - Shutting down application
2025-04-18 01:59:21,072 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 01:59:21,080 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 01:59:21,080 - iceberg-catalog - INFO - [main.py:52] - Database connection closed
2025-04-18 02:18:48,994 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 02:18:49,048 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 02:18:49,048 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 02:18:49,204 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 02:18:49,204 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:12:47,126 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:12:47,128 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:12:47,130 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:12:47,130 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:12:47,332 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:12:47,383 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:12:47,383 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:12:47,544 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:12:47,545 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:13:27,141 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:13:27,144 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:13:27,162 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:13:27,163 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:13:27,371 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:13:27,423 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:13:27,424 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:13:27,577 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:13:27,577 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:14:07,591 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:14:07,595 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:14:07,605 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:14:07,606 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:14:07,768 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:14:07,815 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:14:07,815 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:14:07,963 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:14:07,963 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:16:40,501 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:16:40,505 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:16:40,546 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:16:40,547 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:16:40,736 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:16:40,785 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:16:40,785 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:16:40,935 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:16:40,935 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:19:03,006 - iceberg-catalog - INFO - [config.py:30] - Received request for configuration. Warehouse: None
2025-04-18 09:19:03,008 - iceberg-catalog - INFO - [config.py:26] - Fetching configuration for catalog: default
2025-04-18 09:19:03,045 - iceberg-catalog - INFO - [config.py:32] - Successfully retrieved configuration
2025-04-18 09:21:55,460 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:21:55,461 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:21:55,464 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:21:55,464 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:29:55,580 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:29:55,626 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:29:55,627 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:29:55,794 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:29:55,795 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:30:14,739 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:30:14,742 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:30:14,743 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:30:14,857 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:30:14,860 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: False
2025-04-18 09:30:14,875 - iceberg-catalog - ERROR - [database.py:58] - Database query error: column "table_uuid" of relation "tables" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedColumnError: column "table_uuid" of relation "tables" does not exist
2025-04-18 09:30:14,888 - iceberg-catalog - ERROR - [database.py:108] - Transaction error: column "table_uuid" of relation "tables" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 105, in transaction
    yield conn
  File "/code/app/services/table.py", line 237, in create_table
    table_record = await db.fetch_one(
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedColumnError: column "table_uuid" of relation "tables" does not exist
2025-04-18 09:30:14,889 - iceberg-catalog - ERROR - [table.py:316] - Error creating table: column "table_uuid" of relation "tables" does not exist
Traceback (most recent call last):
  File "/code/app/services/table.py", line 237, in create_table
    table_record = await db.fetch_one(
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedColumnError: column "table_uuid" of relation "tables" does not exist
2025-04-18 09:30:14,889 - iceberg-catalog - ERROR - [tables.py:159] - Error creating table: column "table_uuid" of relation "tables" does not exist
Traceback (most recent call last):
  File "/code/app/api/tables.py", line 109, in create_table
    result = await TableService.create_table(namespace_levels, request, x_iceberg_access_delegation)
  File "/code/app/services/table.py", line 237, in create_table
    table_record = await db.fetch_one(
  File "/code/app/database.py", line 52, in fetch_one
    record = await conn.fetchrow(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 748, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedColumnError: column "table_uuid" of relation "tables" does not exist
2025-04-18 09:32:51,189 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:32:51,191 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:32:51,191 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:32:51,195 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:32:51,198 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: False
2025-04-18 09:32:51,208 - iceberg-catalog - ERROR - [database.py:90] - Database query error: relation "schemas" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 86, in execute
    result = await conn.execute(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 352, in execute
    _, status, _ = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "schemas" does not exist
2025-04-18 09:32:51,209 - iceberg-catalog - ERROR - [database.py:108] - Transaction error: relation "schemas" does not exist
Traceback (most recent call last):
  File "/code/app/database.py", line 105, in transaction
    yield conn
  File "/code/app/services/table.py", line 253, in create_table
    await db.execute(schema_insert_query, table_id, schema_id, json.dumps(schema_json))
  File "/code/app/database.py", line 86, in execute
    result = await conn.execute(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 352, in execute
    _, status, _ = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "schemas" does not exist
2025-04-18 09:32:51,210 - iceberg-catalog - ERROR - [table.py:316] - Error creating table: relation "schemas" does not exist
Traceback (most recent call last):
  File "/code/app/services/table.py", line 253, in create_table
    await db.execute(schema_insert_query, table_id, schema_id, json.dumps(schema_json))
  File "/code/app/database.py", line 86, in execute
    result = await conn.execute(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 352, in execute
    _, status, _ = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "schemas" does not exist
2025-04-18 09:32:51,211 - iceberg-catalog - ERROR - [tables.py:159] - Error creating table: relation "schemas" does not exist
Traceback (most recent call last):
  File "/code/app/api/tables.py", line 109, in create_table
    result = await TableService.create_table(namespace_levels, request, x_iceberg_access_delegation)
  File "/code/app/services/table.py", line 253, in create_table
    await db.execute(schema_insert_query, table_id, schema_id, json.dumps(schema_json))
  File "/code/app/database.py", line 86, in execute
    result = await conn.execute(query, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 352, in execute
    _, status, _ = await self._execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1864, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 1961, in __execute
    result, stmt = await self._do_execute(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2004, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 432, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.UndefinedTableError: relation "schemas" does not exist
2025-04-18 09:35:12,055 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:35:12,057 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:35:12,057 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:35:12,060 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:35:12,062 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: True
2025-04-18 09:35:12,062 - iceberg-catalog - WARNING - [table.py:163] - Table already exists: ['namespace1'].customer_data
2025-04-18 09:35:12,062 - iceberg-catalog - WARNING - [tables.py:133] - Table already exists: Table already exists: ['namespace1'].customer_data
2025-04-18 09:35:41,425 - iceberg-catalog - INFO - [tables.py:324] - Drop table request. prefix: dev, namespace: namespace1, table: customer_data, purge_requested: False
2025-04-18 09:35:41,426 - iceberg-catalog - INFO - [table.py:558] - Dropping table ['namespace1'].customer_data, purge_requested: False
2025-04-18 09:35:41,445 - iceberg-catalog - INFO - [table.py:593] - Dropped table ['namespace1'].customer_data
2025-04-18 09:35:56,572 - iceberg-catalog - INFO - [tables.py:40] - List tables request. prefix: dev, namespace: namespace1, page_token: None, page_size: None
2025-04-18 09:35:56,573 - iceberg-catalog - INFO - [table.py:39] - Listing tables in namespace: ['namespace1']
2025-04-18 09:35:56,573 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:35:56,577 - iceberg-catalog - INFO - [table.py:101] - Found 0 tables in namespace ['namespace1']
2025-04-18 09:36:05,423 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:36:05,424 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:36:05,424 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:36:05,426 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:36:05,428 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: False
2025-04-18 09:36:05,449 - iceberg-catalog - ERROR - [database.py:108] - Transaction error: 1 validation error for SortOrder
order-id
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/code/app/database.py", line 105, in transaction
    yield conn
  File "/code/app/services/table.py", line 285, in create_table
    sort_orders=[request.write_order] if request.write_order else [SortOrder(order_id=0, fields=[])],
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 347, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for SortOrder
order-id
  field required (type=value_error.missing)
2025-04-18 09:36:05,451 - iceberg-catalog - WARNING - [tables.py:146] - Bad request: 1 validation error for SortOrder
order-id
  field required (type=value_error.missing)
2025-04-18 09:38:38,248 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:38:38,252 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:38:38,258 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:38:38,259 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:38:38,445 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:38:38,496 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:38:38,496 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:38:38,651 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:38:38,651 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:39:12,205 - iceberg-catalog - INFO - [tables.py:324] - Drop table request. prefix: dev, namespace: namespace1, table: customer_data, purge_requested: False
2025-04-18 09:39:12,208 - iceberg-catalog - INFO - [table.py:558] - Dropping table ['namespace1'].customer_data, purge_requested: False
2025-04-18 09:39:12,232 - iceberg-catalog - INFO - [table.py:593] - Dropped table ['namespace1'].customer_data
2025-04-18 09:39:42,078 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:39:42,083 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:39:42,083 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:39:42,092 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:39:42,096 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: False
2025-04-18 09:39:42,117 - iceberg-catalog - ERROR - [database.py:108] - Transaction error: 2 validation errors for TableMetadata
format-version
  field required (type=value_error.missing)
table-uuid
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/code/app/database.py", line 105, in transaction
    yield conn
  File "/code/app/services/table.py", line 273, in create_table
    table_metadata = TableMetadata(
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 347, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for TableMetadata
format-version
  field required (type=value_error.missing)
table-uuid
  field required (type=value_error.missing)
2025-04-18 09:39:42,119 - iceberg-catalog - WARNING - [tables.py:146] - Bad request: 2 validation errors for TableMetadata
format-version
  field required (type=value_error.missing)
table-uuid
  field required (type=value_error.missing)
2025-04-18 09:41:43,768 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:41:43,770 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:41:43,782 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:41:43,783 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:41:43,978 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:41:44,027 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:41:44,028 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:41:44,190 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:41:44,191 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:42:06,165 - iceberg-catalog - INFO - [tables.py:324] - Drop table request. prefix: dev, namespace: namespace1, table: customer_data, purge_requested: False
2025-04-18 09:42:06,166 - iceberg-catalog - INFO - [table.py:577] - Dropping table ['namespace1'].customer_data, purge_requested: False
2025-04-18 09:42:06,185 - iceberg-catalog - INFO - [table.py:612] - Dropped table ['namespace1'].customer_data
2025-04-18 09:42:17,753 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data
2025-04-18 09:42:17,759 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data in namespace ['namespace1']
2025-04-18 09:42:17,759 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:42:17,762 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:42:17,764 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: False
2025-04-18 09:42:17,774 - iceberg-catalog - INFO - [table.py:314] - Created table customer_data in namespace ['namespace1'] with UUID 7d314f66-a91a-4788-8405-75b7c13a796c
2025-04-18 09:42:53,040 - iceberg-catalog - INFO - [tables.py:40] - List tables request. prefix: dev, namespace: namespace1, page_token: None, page_size: None
2025-04-18 09:42:53,042 - iceberg-catalog - INFO - [table.py:39] - Listing tables in namespace: ['namespace1']
2025-04-18 09:42:53,043 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 09:42:53,050 - iceberg-catalog - INFO - [table.py:101] - Found 1 tables in namespace ['namespace1']
2025-04-18 09:43:17,194 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 09:43:17,200 - iceberg-catalog - INFO - [table.py:380] - Loading table ['namespace1'].customer_data
2025-04-18 09:43:17,210 - iceberg-catalog - WARNING - [tables.py:228] - Bad request: 2 validation errors for TableMetadata
format-version
  field required (type=value_error.missing)
table-uuid
  field required (type=value_error.missing)
2025-04-18 09:46:18,655 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:46:18,658 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:46:18,671 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:46:18,671 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:46:18,910 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:46:18,964 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:46:18,965 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:46:19,116 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:46:19,116 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:46:32,376 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 09:46:32,377 - iceberg-catalog - INFO - [table.py:380] - Loading table ['namespace1'].customer_data
2025-04-18 09:46:32,391 - iceberg-catalog - WARNING - [tables.py:228] - Bad request: 1 validation error for TableMetadata
table-uuid
  str type expected (type=type_error.str)
2025-04-18 09:47:30,868 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:47:30,871 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:47:30,884 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:47:30,885 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:47:31,111 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:47:34,045 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:47:34,096 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:47:34,097 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:47:34,249 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:47:34,249 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 09:47:41,555 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 09:47:41,556 - iceberg-catalog - INFO - [table.py:380] - Loading table ['namespace1'].customer_data
2025-04-18 09:47:41,566 - iceberg-catalog - INFO - [table.py:565] - Loaded table ['namespace1'].customer_data
2025-04-18 09:47:59,389 - iceberg-catalog - INFO - [tables.py:275] - Check table exists request. prefix: dev, namespace: namespace1, table: customer_data
2025-04-18 09:47:59,390 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data
2025-04-18 09:47:59,393 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data exists: True
2025-04-18 09:48:15,476 - iceberg-catalog - INFO - [tables.py:403] - Load credentials request. prefix: dev, namespace: namespace1, table: customer_data
2025-04-18 09:48:15,477 - iceberg-catalog - INFO - [table.py:656] - Loading credentials for table ['namespace1'].customer_data
2025-04-18 09:48:15,487 - iceberg-catalog - INFO - [table.py:698] - Loaded 0 credential(s) for table ['namespace1'].customer_data
2025-04-18 09:48:15,489 - iceberg-catalog - WARNING - [tables.py:422] - Bad request: 1 validation error for LoadCredentialsResponse
storage-credentials
  field required (type=value_error.missing)
2025-04-18 09:50:26,386 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 09:50:26,389 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 09:50:26,401 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 09:50:26,401 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 09:50:26,603 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 09:50:26,658 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 09:50:26,658 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 09:50:26,816 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 09:50:26,816 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 10:07:47,668 - iceberg-catalog - INFO - [tables.py:403] - Load credentials request. prefix: dev, namespace: namespace1, table: customer_data
2025-04-18 10:07:47,671 - iceberg-catalog - INFO - [table.py:656] - Loading credentials for table ['namespace1'].customer_data
2025-04-18 10:07:47,716 - iceberg-catalog - INFO - [table.py:698] - Loaded 0 credential(s) for table ['namespace1'].customer_data
2025-04-18 10:18:35,243 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 10:18:35,247 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:18:35,249 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:18:35,249 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 10:18:35,511 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:18:35,563 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 10:18:35,563 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:18:35,729 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:18:35,729 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 10:18:53,269 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 10:18:53,271 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:18:53,283 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:18:53,283 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 10:18:53,471 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:18:53,539 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 10:18:53,539 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:18:53,702 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:18:53,702 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 10:19:14,462 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 10:19:14,469 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:19:14,509 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:19:14,509 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 10:19:14,691 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:19:14,739 - iceberg-catalog - INFO - [main.py:45] - Starting up application
2025-04-18 10:19:14,740 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:19:14,893 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:19:14,894 - iceberg-catalog - INFO - [main.py:47] - Database connection established
2025-04-18 10:19:30,230 - iceberg-catalog - INFO - [main.py:51] - Shutting down application
2025-04-18 10:19:30,233 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:19:30,245 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:19:30,246 - iceberg-catalog - INFO - [main.py:53] - Database connection closed
2025-04-18 10:19:30,409 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:19:33,912 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:19:33,959 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:19:33,960 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:19:34,112 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:19:34,112 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:19:58,418 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:19:58,422 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:19:58,438 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:19:58,439 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:19:58,628 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:19:58,692 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:19:58,693 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:19:58,845 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:19:58,846 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:22:54,461 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:22:54,465 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:22:54,481 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:22:54,481 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:22:54,665 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:22:54,717 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:22:54,717 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:22:54,874 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:22:54,874 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:23:50,628 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:23:50,633 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:23:50,651 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:23:50,651 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:23:50,837 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:23:58,143 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:23:58,196 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:23:58,196 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:23:58,353 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:23:58,354 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:25:08,185 - iceberg-catalog - INFO - [credentials.py:24] - Creating credentials for prefix: dev, warehouse: s3://300289082521-my-warehouse/dev/
2025-04-18 10:25:08,200 - iceberg-catalog - INFO - [credentials.py:54] - Credentials created/updated with ID: 1
2025-04-18 10:25:19,870 - iceberg-catalog - INFO - [credentials.py:24] - Creating credentials for prefix: dev, warehouse: s3://300289082521-my-warehouse/dev/
2025-04-18 10:25:19,887 - iceberg-catalog - INFO - [credentials.py:54] - Credentials created/updated with ID: 1
2025-04-18 10:25:52,433 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:25:52,436 - iceberg-catalog - INFO - [table.py:404] - Loading table ['namespace1'].customer_data
2025-04-18 10:25:52,446 - iceberg-catalog - INFO - [table.py:589] - Loaded table ['namespace1'].customer_data
2025-04-18 10:27:13,708 - iceberg-catalog - INFO - [tables.py:107] - Create table request. prefix: dev, namespace: namespace1, table name: customer_data1
2025-04-18 10:27:13,710 - iceberg-catalog - INFO - [table.py:152] - Creating table customer_data1 in namespace ['namespace1']
2025-04-18 10:27:13,710 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 10:27:13,715 - iceberg-catalog - INFO - [table.py:124] - Checking if table exists: ['namespace1'].customer_data1
2025-04-18 10:27:13,717 - iceberg-catalog - INFO - [table.py:137] - Table ['namespace1'].customer_data1 exists: False
2025-04-18 10:27:13,750 - iceberg-catalog - INFO - [table.py:338] - Created table customer_data1 in namespace ['namespace1'] with UUID cfa2ee62-34bb-4ebc-913d-337464ffa1eb
2025-04-18 10:27:23,773 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data1, snapshots: None
2025-04-18 10:27:23,775 - iceberg-catalog - INFO - [table.py:404] - Loading table ['namespace1'].customer_data1
2025-04-18 10:27:23,783 - iceberg-catalog - INFO - [table.py:589] - Loaded table ['namespace1'].customer_data1
2025-04-18 10:28:15,279 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:28:15,282 - iceberg-catalog - INFO - [table.py:404] - Loading table ['namespace1'].customer_data
2025-04-18 10:28:15,288 - iceberg-catalog - INFO - [table.py:435] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:29:34,882 - iceberg-catalog - INFO - [tables.py:40] - List tables request. prefix: dev, namespace: namespace1, page_token: None, page_size: None
2025-04-18 10:29:34,886 - iceberg-catalog - INFO - [table.py:39] - Listing tables in namespace: ['namespace1']
2025-04-18 10:29:34,886 - iceberg-catalog - INFO - [namespace.py:195] - Checking if namespace exists: ['namespace1']
2025-04-18 10:29:34,921 - iceberg-catalog - INFO - [table.py:101] - Found 2 tables in namespace ['namespace1']
2025-04-18 10:29:50,277 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data1, snapshots: None
2025-04-18 10:29:50,278 - iceberg-catalog - INFO - [table.py:404] - Loading table ['namespace1'].customer_data1
2025-04-18 10:29:50,283 - iceberg-catalog - INFO - [table.py:435] - Table ['namespace1'].customer_data1 not modified, returning 304
2025-04-18 10:35:24,722 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:35:24,724 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:35:24,725 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:35:24,726 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:35:24,920 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:35:25,143 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:35:25,143 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:35:25,305 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:35:25,306 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:36:08,111 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:36:08,114 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:36:08,133 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:36:08,133 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:36:08,415 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:36:08,468 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:36:08,469 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:36:08,623 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:36:08,623 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:36:45,063 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:36:45,064 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:36:45,078 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:36:45,079 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:36:45,261 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:36:45,313 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:36:45,314 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:36:45,464 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:36:45,464 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:36:52,003 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:36:52,005 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:36:52,015 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:36:52,016 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:36:52,167 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:36:52,221 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:36:52,221 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:36:52,366 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:36:52,367 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:37:00,574 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:37:00,576 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:37:00,586 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:37:00,587 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:37:00,753 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:37:00,803 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:37:00,804 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:37:01,040 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:37:01,040 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:37:10,283 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:37:10,287 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:37:10,295 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:37:10,295 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:37:10,441 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:37:10,493 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:37:10,493 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:37:10,643 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:37:10,643 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:38:34,703 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:38:34,705 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:38:34,723 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:38:34,723 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:38:34,917 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:38:34,973 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:38:34,973 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:38:35,136 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:38:35,136 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:38:39,840 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:38:39,842 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:38:39,853 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:38:39,854 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:38:40,015 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:38:40,064 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:38:40,064 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:38:40,215 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:38:40,215 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:39:01,391 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:39:01,393 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data
2025-04-18 10:39:01,457 - iceberg-catalog - INFO - [table.py:626] - Loaded table ['namespace1'].customer_data
2025-04-18 10:39:01,460 - iceberg-catalog - INFO - [table.py:427] - Returning 1 credentials for table ID: 4
2025-04-18 10:39:01,461 - iceberg-catalog - WARNING - [tables.py:213] - No storage credentials found for table
2025-04-18 10:39:36,725 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data1, snapshots: None
2025-04-18 10:39:36,727 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data1
2025-04-18 10:39:36,731 - iceberg-catalog - INFO - [table.py:472] - Table ['namespace1'].customer_data1 not modified, returning 304
2025-04-18 10:39:43,461 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:39:43,462 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data
2025-04-18 10:39:43,467 - iceberg-catalog - INFO - [table.py:472] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:39:58,922 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:39:58,924 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data
2025-04-18 10:39:58,928 - iceberg-catalog - INFO - [table.py:472] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:40:27,512 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:40:27,514 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data
2025-04-18 10:40:27,518 - iceberg-catalog - INFO - [table.py:472] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:40:41,090 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:40:41,093 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:40:41,108 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:40:41,108 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:40:41,294 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:40:41,354 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:40:41,354 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:40:41,507 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:40:41,508 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:41:16,655 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:41:16,657 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:41:16,665 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:41:16,665 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:41:27,213 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:41:27,261 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:41:27,261 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:41:27,421 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:41:27,422 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:42:16,678 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:42:16,680 - iceberg-catalog - INFO - [table.py:441] - Loading table ['namespace1'].customer_data
2025-04-18 10:42:16,702 - iceberg-catalog - INFO - [table.py:472] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:46:52,762 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:46:52,764 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:46:52,770 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:46:52,770 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:46:52,956 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:46:53,010 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:46:53,010 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:46:53,162 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:46:53,163 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:47:41,060 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:47:41,063 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:47:41,097 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:47:41,098 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:47:41,270 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:47:41,328 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:47:41,329 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:47:41,623 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:47:41,623 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:47:48,885 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:47:48,887 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:47:48,892 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:47:48,892 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:47:49,048 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:47:49,104 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:47:49,104 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:47:49,255 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:47:49,255 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:47:59,145 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:47:59,148 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:47:59,162 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:47:59,162 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:47:59,347 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:47:59,397 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:47:59,398 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:47:59,556 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:47:59,557 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:48:45,926 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:48:45,929 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:48:45,941 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:48:45,942 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:48:46,185 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:48:46,244 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:48:46,245 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:48:46,457 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:48:46,458 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:49:07,303 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:49:07,306 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:49:07,322 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:49:07,322 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:49:07,512 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:49:07,562 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:49:07,562 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:49:07,729 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:49:07,729 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:49:09,702 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:49:09,703 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:49:09,709 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:49:09,709 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:49:09,867 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:49:09,923 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:49:09,923 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:49:10,072 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:49:10,072 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:49:26,433 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:49:26,434 - iceberg-catalog - INFO - [table.py:462] - Loading table ['namespace1'].customer_data
2025-04-18 10:49:26,463 - iceberg-catalog - INFO - [table.py:493] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:49:43,959 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:49:43,960 - iceberg-catalog - INFO - [table.py:462] - Loading table ['namespace1'].customer_data
2025-04-18 10:49:43,962 - iceberg-catalog - INFO - [table.py:493] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:49:58,245 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:49:58,245 - iceberg-catalog - INFO - [table.py:462] - Loading table ['namespace1'].customer_data
2025-04-18 10:49:58,246 - iceberg-catalog - INFO - [table.py:493] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:50:33,293 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:50:33,296 - iceberg-catalog - INFO - [table.py:462] - Loading table ['namespace1'].customer_data
2025-04-18 10:50:33,299 - iceberg-catalog - INFO - [table.py:493] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 10:50:39,811 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 10:50:39,814 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 10:50:39,821 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 10:50:39,821 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 10:50:49,364 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 10:50:49,412 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 10:50:49,412 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 10:50:49,565 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 10:50:49,566 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 10:51:00,087 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 10:51:00,087 - iceberg-catalog - INFO - [table.py:462] - Loading table ['namespace1'].customer_data
2025-04-18 10:51:00,115 - iceberg-catalog - INFO - [table.py:493] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:00:02,207 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:00:02,210 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:00:02,211 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:00:02,212 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:00:02,395 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:00:02,451 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:00:02,451 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:00:02,618 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:00:02,618 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:00:35,541 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:00:35,543 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:00:35,555 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:00:35,555 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:00:35,729 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:00:35,780 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:00:35,781 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:00:36,013 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:00:36,020 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:01:37,161 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:01:37,162 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:01:37,168 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:01:37,168 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:01:37,325 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:02:05,777 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:02:29,429 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:02:29,482 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:02:29,482 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:02:29,652 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:02:29,653 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:03:07,993 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:03:08,015 - iceberg-catalog - INFO - [table.py:456] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:03:08,024 - iceberg-catalog - INFO - [table.py:550] - Returning 1 credentials for table ID: 4
2025-04-18 11:03:08,024 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:04:07,464 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:04:07,466 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:04:07,474 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:04:07,474 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:04:15,737 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:04:15,784 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:04:15,785 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:04:15,942 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:04:15,943 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:04:24,608 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:04:24,657 - iceberg-catalog - INFO - [table.py:456] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:04:24,665 - iceberg-catalog - INFO - [table.py:550] - Returning 1 credentials for table ID: 4
2025-04-18 11:04:24,665 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:04:32,018 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:04:32,020 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:04:32,035 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:04:32,036 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:04:32,210 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:04:32,259 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:04:32,260 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:04:32,408 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:04:32,408 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:05:37,263 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:05:37,265 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:05:37,278 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:05:37,279 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:05:37,458 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:05:37,512 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:05:37,512 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:05:37,667 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:05:37,667 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:05:59,774 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:05:59,802 - iceberg-catalog - INFO - [table.py:456] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:05:59,806 - iceberg-catalog - INFO - [table.py:550] - Returning 1 credentials for table ID: 4
2025-04-18 11:05:59,807 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:07:10,356 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:07:10,358 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:07:10,373 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:07:10,373 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:07:10,538 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:07:10,588 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:07:10,588 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:07:10,744 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:07:10,745 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:07:18,998 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:07:19,021 - iceberg-catalog - INFO - [table.py:456] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:07:19,025 - iceberg-catalog - INFO - [table.py:550] - Returning 1 credentials for table ID: 4
2025-04-18 11:07:19,026 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:11:01,485 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:11:01,488 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:11:01,503 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:11:01,503 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:11:21,072 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:11:21,122 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:11:21,122 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:11:21,312 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:11:21,313 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:11:38,285 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:11:38,310 - iceberg-catalog - INFO - [table.py:456] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:11:38,315 - iceberg-catalog - INFO - [table.py:550] - Returning 1 credentials for table ID: 4
2025-04-18 11:11:38,315 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:19:58,990 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:19:58,993 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:19:58,994 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:19:58,995 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:19:59,268 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:19:59,333 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:19:59,334 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:19:59,507 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:19:59,507 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:20:12,513 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:20:12,515 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:20:12,528 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:20:12,529 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:20:12,752 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:20:12,814 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:20:12,815 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:20:13,051 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:20:13,052 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:20:52,324 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:20:52,327 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:20:52,340 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:20:52,341 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:20:52,525 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:20:52,574 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:20:52,574 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:20:52,724 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:20:52,724 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:21:07,743 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:21:07,762 - iceberg-catalog - INFO - [table.py:466] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:21:07,764 - iceberg-catalog - INFO - [table.py:406] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 11:21:07,767 - iceberg-catalog - INFO - [table.py:560] - Returning 1 credentials for table ID: 4
2025-04-18 11:21:07,768 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:23:08,335 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:23:08,339 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:23:08,356 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:23:08,356 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:23:08,607 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:23:08,666 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:23:08,667 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:23:08,823 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:23:08,824 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:33:18,240 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:33:18,242 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:33:18,243 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:33:18,244 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:33:18,448 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:33:18,514 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:33:18,514 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:33:18,666 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:33:18,668 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:33:23,148 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:33:23,150 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:33:23,157 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:33:23,157 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:33:35,499 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:33:35,547 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:33:35,547 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:33:35,722 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:33:35,723 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:33:51,360 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:33:51,408 - iceberg-catalog - INFO - [table.py:466] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:33:51,411 - iceberg-catalog - INFO - [table.py:406] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 11:33:51,415 - iceberg-catalog - INFO - [table.py:810] - Returning 1 credentials for table ID: 4
2025-04-18 11:33:51,415 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 11:36:28,640 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:36:28,643 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:36:28,654 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:36:28,654 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:36:28,845 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:36:28,909 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:36:28,910 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:36:29,074 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:36:29,075 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:36:38,787 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 11:36:38,789 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 11:36:38,802 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 11:36:38,803 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 11:36:38,974 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 11:36:39,028 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 11:36:39,028 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 11:36:39,187 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 11:36:39,187 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 11:36:44,330 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 11:36:44,335 - iceberg-catalog - INFO - [table.py:468] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 11:36:44,338 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 11:36:44,341 - iceberg-catalog - INFO - [table.py:812] - Returning 1 credentials for table ID: 4
2025-04-18 11:36:44,341 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 14:34:49,817 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 14:34:49,861 - iceberg-catalog - INFO - [table.py:468] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 14:34:49,863 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 14:34:49,864 - iceberg-catalog - INFO - [table.py:812] - Returning 1 credentials for table ID: 4
2025-04-18 14:34:49,864 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 14:45:30,757 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 14:45:30,759 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 14:45:30,761 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 14:45:30,761 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 14:45:30,966 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 14:45:31,025 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 14:45:31,025 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 14:45:31,193 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 14:45:31,194 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 14:45:34,211 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 14:45:34,213 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 14:45:34,227 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 14:45:34,228 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 14:45:34,389 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 14:45:34,442 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 14:45:34,443 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 14:45:34,616 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 14:45:34,616 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 14:47:07,600 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 14:47:07,603 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 14:47:07,614 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 14:47:07,614 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 14:47:07,802 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 14:47:07,857 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 14:47:07,857 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 14:47:08,011 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 14:47:08,011 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 14:47:26,943 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 14:47:26,962 - iceberg-catalog - INFO - [table.py:468] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 14:47:26,965 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 14:47:26,967 - iceberg-catalog - INFO - [table.py:993] - Returning 1 credentials for table ID: 4
2025-04-18 14:47:26,968 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 14:47:45,344 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 14:47:45,347 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 14:47:45,363 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 14:47:45,363 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 14:47:45,557 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 14:47:45,615 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 14:47:45,615 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 14:47:45,774 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 14:47:45,774 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 14:48:14,604 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 14:48:14,628 - iceberg-catalog - INFO - [table.py:468] - Table ['namespace1'].customer_data not modified, returning 304
2025-04-18 14:48:14,631 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 14:48:14,633 - iceberg-catalog - INFO - [table.py:993] - Returning 1 credentials for table ID: 4
2025-04-18 14:48:14,633 - iceberg-catalog - INFO - [tables.py:209] - Table ['namespace1'].customer_data not modified, returning 304 with credentials
2025-04-18 14:49:03,845 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 14:49:03,848 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 14:49:03,883 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 14:49:03,884 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
2025-04-18 14:49:04,066 - iceberg-catalog - INFO - [database.py:17] - Initializing database with connection string: postgres:5432/iceberg_catalog
2025-04-18 14:49:04,116 - iceberg-catalog - INFO - [main.py:46] - Starting up application
2025-04-18 14:49:04,117 - iceberg-catalog - INFO - [database.py:22] - Connecting to database...
2025-04-18 14:49:04,270 - iceberg-catalog - INFO - [database.py:26] - Successfully connected to database
2025-04-18 14:49:04,270 - iceberg-catalog - INFO - [main.py:48] - Database connection established
2025-04-18 14:50:17,331 - iceberg-catalog - INFO - [tables.py:196] - Load table request. prefix: dev, namespace: namespace1, table: customer_data, snapshots: None
2025-04-18 14:50:17,340 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 14:50:17,343 - iceberg-catalog - INFO - [table.py:993] - Returning 1 credentials for table ID: 4
2025-04-18 14:50:17,356 - iceberg-catalog - INFO - [table.py:408] - Using credential with prefix=dev, warehouse=s3://300289082521-my-warehouse/dev/
2025-04-18 14:50:17,357 - iceberg-catalog - INFO - [table.py:993] - Returning 1 credentials for table ID: 4
2025-04-18 15:28:01,086 - iceberg-catalog - INFO - [main.py:52] - Shutting down application
2025-04-18 15:28:01,090 - iceberg-catalog - INFO - [database.py:35] - Disconnecting from database...
2025-04-18 15:28:01,091 - iceberg-catalog - INFO - [database.py:39] - Database connections closed
2025-04-18 15:28:01,091 - iceberg-catalog - INFO - [main.py:54] - Database connection closed
